Add mpv-version.
kljohann/mpv.el pull request #9
Opened 2021-02-03 13:45 UTC by firmart

Motivation: [mpv 0.33](https://github.com/mpv-player/mpv/commit/e9e93b4dbe748cd341a6fbea355e6ba013ada81b) introduces lots of playlist command. It would thus make sense to compare `mpv` version string to see if a command is supported or not.

2021-02-04 20:13 UTC, kljohann requested changes
Thanks, this looks great! I have three minor suggestions that you could maybe adopt?

2021-02-04 20:13 UTC, kljohann commented on mpv.el
> +	  (message "%s" version)))))
Generally the `…-version` interactive commands in Emacs seem to also display the program name: 
```suggestion
	  (message "mpv %s" version)))))
```
We _could_ also print the full first line of the `--version` output, or even the complete output? (Only during interactive use, the function would still only return the "reduced" version.)

2021-02-04 20:13 UTC, kljohann commented on mpv.el
> +  "Return mpv version."
Maybe also explain the behavior on interactive use here? Something like the following, perhaps?
```suggestion
  "Return the mpv version string.
When called interactively, also show a more verbose version in
the echo area."
```

2021-02-05 05:53 UTC, firmart commented
Thanks for the suggestion. I adopted them.

2021-02-07 11:39 UTC, kljohann approved these changes

2021-02-07 11:40 UTC, merged